//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Ceny
    {
        public int Id { get; set; }
        [DisplayName("Cennik")]
        public Nullable<int> CennikId { get; set; }
        [DisplayName("Towar")]
        public Nullable<int> TowarId { get; set; }
        public decimal Cena { get; set; }
        public Nullable<decimal> Rabat { get; set; }
    }
}
