//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Towary
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Masa { get; set; }
        public string JM { get; set; }
        [DisplayName("Data Utworzenia")]
        public Nullable<System.DateTime> Data_Utworzenia { get; set; }
        [DisplayName("Data Modyfikacji")]
        public Nullable<System.DateTime> Data_Modyfikacji { get; set; }

        public override string ToString()
        {
            return Nazwa;
        }
    }
}
