//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string AcceptRemoveText {
            get {
                return ResourceManager.GetString("AcceptRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string AddBtnText {
            get {
                return ResourceManager.GetString("AddBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod jest nieprawidłowy.
        /// </summary>
        internal static string CodeWarning {
            get {
                return ResourceManager.GetString("CodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat może być tylko od 1 do 100%.
        /// </summary>
        internal static string DiscountLengthWarning {
            get {
                return ResourceManager.GetString("DiscountLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat jest nieprawidłowa.
        /// </summary>
        internal static string DiscountWarning {
            get {
                return ResourceManager.GetString("DiscountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv.
        /// </summary>
        internal static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość kodu powinna być 7 znaków.
        /// </summary>
        internal static string LengthCodeWarning {
            get {
                return ResourceManager.GetString("LengthCodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa ma być od 1 do 255 znaków.
        /// </summary>
        internal static string NameWarning {
            get {
                return ResourceManager.GetString("NameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena nie jest wpisana.
        /// </summary>
        internal static string NullPriceWarning {
            get {
                return ResourceManager.GetString("NullPriceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena jest nieprawidłowa.
        /// </summary>
        internal static string PriceWarning {
            get {
                return ResourceManager.GetString("PriceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś pewien że chcesz usunąć?.
        /// </summary>
        internal static string RemoveQuestion {
            get {
                return ResourceManager.GetString("RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz csv plik.
        /// </summary>
        internal static string TitleSaveDialog {
            get {
                return ResourceManager.GetString("TitleSaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string UpdateBtnText {
            get {
                return ResourceManager.GetString("UpdateBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa jest nieprawidłowa.
        /// </summary>
        internal static string WeightWarning {
            get {
                return ResourceManager.GetString("WeightWarning", resourceCulture);
            }
        }
    }
}
